// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyChannel.proto

package gRPC_Project;

public interface callResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string callingOut = 1;</code>
   */
  java.lang.String getCallingOut();
  /**
   * <code>string callingOut = 1;</code>
   */
  com.google.protobuf.ByteString
      getCallingOutBytes();
}
