// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyChannel.proto

package gRPC_Project;

public interface callRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:callRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string callingIn = 1;</code>
   */
  java.lang.String getCallingIn();
  /**
   * <code>string callingIn = 1;</code>
   */
  com.google.protobuf.ByteString
      getCallingInBytes();
}
