// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControlService.proto

package gRPC_Project;

public interface cameraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cameraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *bool because is true or false statement, and 1 is just a tag not its content
   * </pre>
   *
   * <code>bool turnCameraOn = 1;</code>
   */
  boolean getTurnCameraOn();
}
