// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControlService.proto

package gRPC_Project;

public interface cameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool turnCameraOff = 1;</code>
   */
  boolean getTurnCameraOff();
}
