// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyChannel.proto

package gRPC_Project;

public interface locationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:locationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sendLocation = 1;</code>
   */
  java.lang.String getSendLocation();
  /**
   * <code>string sendLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getSendLocationBytes();
}
