// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyChannel.proto

package gRPC_Project;

public interface locationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:locationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receivedLocation = 1;</code>
   */
  java.lang.String getReceivedLocation();
  /**
   * <code>string receivedLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getReceivedLocationBytes();
}
