// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoiseSoundRecognition.proto

package gRPC_Project;

public interface messageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string textMessage = 1;</code>
   */
  java.lang.String getTextMessage();
  /**
   * <code>string textMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextMessageBytes();
}
