// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoiseSoundRecognition.proto

package gRPC_Project;

public interface messageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string textMessageOut = 1;</code>
   */
  java.lang.String getTextMessageOut();
  /**
   * <code>string textMessageOut = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextMessageOutBytes();
}
