// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControlService.proto

package gRPC_Project;

public interface recordingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recordingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recordingOn = 1;</code>
   */
  java.lang.String getRecordingOn();
  /**
   * <code>string recordingOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecordingOnBytes();
}
