// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControlService.proto

package gRPC_Project;

public interface recordingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recordingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recordingOutput = 1;</code>
   */
  java.lang.String getRecordingOutput();
  /**
   * <code>string recordingOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecordingOutputBytes();
}
