// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoiseSoundRecognition.proto

package gRPC_Project;

public interface textRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:textRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
