// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoiseSoundRecognition.proto

package gRPC_Project;

public interface textResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:textResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string noiseToTex = 1;</code>
   */
  java.lang.String getNoiseToTex();
  /**
   * <code>string noiseToTex = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoiseToTexBytes();
}
